apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: sock-shop
spec:
  goTemplate: true
  goTemplateOptions: ["missingkey=error"]
  generators:
  - list:
      elements:
      - cluster: mumbai
        url: # mumbai-cluster-url
      - cluster: us
        url: # us-cluster-url
  template:
    metadata:
      name: '{{.cluster}}-sock-shop'
    spec:
      project: default
      source:
        repoURL: https://github.com/semever24/argocd-applicationset-controller.git
        targetRevision: master
        path: sock-shop
      destination:
        server: '{{.url}}'
        namespace: default
      syncPolicy:
        automated:
          prune: true
          selfHeal: true
        syncOptions:
        - CreateNamespace=true