apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: sock-shop
spec:
  goTemplate: true
  goTemplateOptions: ["missingkey=error"]
  generators:
  - list:
      elements:
      - cluster: mumbai
        url: https://71E1C3A4774230A924C9869C5A5F82EE.gr7.ap-south-1.eks.amazonaws.com
      - cluster: us
        url: https://683E2FFAC9FAD3E68E95D5C5EAE6F35C.gr7.us-east-1.eks.amazonaws.com
  template:
    metadata:
      name: '{{.cluster}}-sock-shop'
    spec:
      project: default
      source:
        repoURL: https://github.com/semever24/argocd-applicationset-controller.git
        targetRevision: master
        path: sock-shop
      destination:
        server: '{{.url}}'
        namespace: default
      syncPolicy:
        automated:
          prune: true
          selfHeal: true
        syncOptions:
        - CreateNamespace=true